os:
  - linux
  - windows
  - osx

language: node_js
node_js:
- 14

script:
  - npm run build
  - npm run test

after_success:
  - node deploy.js success $WEBHOOK_URL

after_failure:
  - node deploy.js failure $WEBHOOK_URL

branches:
  only:
  - main

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: build/**/*
  cleanup: true
  on:
    tags: true
