os:
  - linux
  - windows
  - osx

language: node_js
node_js:
- 14

script:
  - npm run c
  - npm run service
  - npm run ct
  - npm run test
  - npm run zip

after_success:
  - node deploy.js success $WEBHOOK_URL

after_failure:
  - node deploy.js failure $WEBHOOK_URL

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: build/coinsswap-token-list.zip
  cleanup: false
  on:
    tags: true
